### ISSUE TITLE
Chat with other users

### ISSUE THREAD

**Issue by rluetzner** [7/CoronaExchange#11]
To actually trade items, users must contact each other and organize where they meet for the transaction.

Messages from a chat should be stored in a database.

**Comment by aweisser** [comment]
I created a branch chat-backend for this and pushed a first commit.

**Comment by rluetzner** [comment]
Looks good for a first draft. We should implement a POST endpoint as well to add new messages.

New messages can be kept in memory for now.

**Comment by rluetzner** [comment]
This was solved by #32 .
