### ISSUE TITLE
Server returns a limited list of items for a given Geolocation

### ISSUE THREAD

**Issue by rluetzner** [7/CoronaExchange#2]

**Comment by rluetzner** [comment]
Sounds good to me. What values should the response contain? Obviously:
- **Which user** is offereing.
- What are they **offering**.
- The exact (or approximate) **location**.
- What they want to **trade for**.

Am I missing something?

**Comment by aweisser** [comment]
Currently we don't have users. So I would skip this atm. We can add users as part of a later user story, after we implemented the user authentication.

**Comment by aweisser** [comment]
The location should be a geo location (in GoogleMaps API it's something like `{lat: -34.397, lng: 150.644}`.
The "offering" and "tradefor" should contain a name and a capacity.

**Comment by aweisser** [comment]
The response should be sorted by distance to the given zipcode and I think we need a pagination.

**Comment by aweisser** [comment]
I would recommend using HATEOAS from day 1.
https://en.wikipedia.org/wiki/HATEOAS

**Comment by rluetzner** [comment]
Do we want to use this library for HATEOAS: https://www.npmjs.com/package/express-hateoas-links ?

**Comment by aweisser** [comment]
As discussed the search request should always return offerings depending on the current map rectangle (long/lat). So the rectangle must bei part of the query params.

**Comment by rluetzner** [comment]
We decided that we would use a rectangle to filter offerings, we will skip implementing pagination for now.

**Comment by rluetzner** [comment]
@aweisser , do you still think we should provide HATEOAS? There is currently only a single endpoint available. I think this should be part of a separate issue which we can include later, when we have at least 2 endpoints.
